
(define (problem knights-tour-problem-8x8) 
   (:domain knights-tour)

   (:objects 
      A1 A2 A3 A4 A5 A6 A7 A8 
      B1 B2 B3 B4 B5 B6 B7 B8 
      C1 C2 C3 C4 C5 C6 C7 C8 
      D1 D2 D3 D4 D5 D6 D7 D8 
      E1 E2 E3 E4 E5 E6 E7 E8 
      F1 F2 F3 F4 F5 F6 F7 F8 
      G1 G2 G3 G4 G5 G6 G7 G8 
      H1 H2 H3 H4 H5 H6 H7 H8 

   (:init 
      ;The Knight's starting square is arbitrary
      ; here, we have ; chosen the upper right corner. 
      (at A8) 
      (visited A8)
      
      ; We have to list all valid moves: 
       (valid_move A1 C2)
       (valid_move A1 B3)
       (valid_move B1 A3)
       (valid_move B1 D2)
       (valid_move B1 C3)
       (valid_move C1 A2)
       (valid_move C1 B3)
       (valid_move C1 E2)
       (valid_move C1 D3)
       (valid_move D1 B2)
       (valid_move D1 C3)
       (valid_move D1 F2)
       (valid_move D1 E3)
       (valid_move E1 C2)
       (valid_move E1 D3)
       (valid_move E1 G2)
       (valid_move E1 F3)
       (valid_move F1 D2)
       (valid_move F1 E3)
       (valid_move F1 H2)
       (valid_move F1 G3)
       (valid_move G1 E2)
       (valid_move G1 F3)
       (valid_move G1 H3)
       (valid_move H1 F2)
       (valid_move H1 G3)
       (valid_move A2 C1)
       (valid_move A2 C3)
       (valid_move A2 B4)
       (valid_move B2 A4)
       (valid_move B2 D1)
       (valid_move B2 D3)
       (valid_move B2 C4)
       (valid_move C2 A1)
       (valid_move C2 A3)
       (valid_move C2 B4)
       (valid_move C2 E1)
       (valid_move C2 E3)
       (valid_move C2 D4)
       (valid_move D2 B1)
       (valid_move D2 B3)
       (valid_move D2 C4)
       (valid_move D2 F1)
       (valid_move D2 F3)
       (valid_move D2 E4)
       (valid_move E2 C1)
       (valid_move E2 C3)
       (valid_move E2 D4)
       (valid_move E2 G1)
       (valid_move E2 G3)
       (valid_move E2 F4)
       (valid_move F2 D1)
       (valid_move F2 D3)
       (valid_move F2 E4)
       (valid_move F2 H1)
       (valid_move F2 H3)
       (valid_move F2 G4)
       (valid_move G2 E1)
       (valid_move G2 E3)
       (valid_move G2 F4)
       (valid_move G2 H4)
       (valid_move H2 F1)
       (valid_move H2 F3)
       (valid_move H2 G4)
       (valid_move A3 C2)
       (valid_move A3 C4)
       (valid_move A3 B5)
       (valid_move A3 B1)
       (valid_move B3 A5)
       (valid_move B3 A1)
       (valid_move B3 D2)
       (valid_move B3 D4)
       (valid_move B3 C5)
       (valid_move B3 C1)
       (valid_move C3 A2)
       (valid_move C3 A4)
       (valid_move C3 B5)
       (valid_move C3 B1)
       (valid_move C3 E2)
       (valid_move C3 E4)
       (valid_move C3 D5)
       (valid_move C3 D1)
       (valid_move D3 B2)
       (valid_move D3 B4)
       (valid_move D3 C5)
       (valid_move D3 C1)
       (valid_move D3 F2)
       (valid_move D3 F4)
       (valid_move D3 E5)
       (valid_move D3 E1)
       (valid_move E3 C2)
       (valid_move E3 C4)
       (valid_move E3 D5)
       (valid_move E3 D1)
       (valid_move E3 G2)
       (valid_move E3 G4)
       (valid_move E3 F5)
       (valid_move E3 F1)
       (valid_move F3 D2)
       (valid_move F3 D4)
       (valid_move F3 E5)
       (valid_move F3 E1)
       (valid_move F3 H2)
       (valid_move F3 H4)
       (valid_move F3 G5)
       (valid_move F3 G1)
       (valid_move G3 E2)
       (valid_move G3 E4)
       (valid_move G3 F5)
       (valid_move G3 F1)
       (valid_move G3 H5)
       (valid_move G3 H1)
       (valid_move H3 F2)
       (valid_move H3 F4)
       (valid_move H3 G5)
       (valid_move H3 G1)
       (valid_move A4 C3)
       (valid_move A4 C5)
       (valid_move A4 B6)
       (valid_move A4 B2)
       (valid_move B4 A6)
       (valid_move B4 A2)
       (valid_move B4 D3)
       (valid_move B4 D5)
       (valid_move B4 C6)
       (valid_move B4 C2)
       (valid_move C4 A3)
       (valid_move C4 A5)
       (valid_move C4 B6)
       (valid_move C4 B2)
       (valid_move C4 E3)
       (valid_move C4 E5)
       (valid_move C4 D6)
       (valid_move C4 D2)
       (valid_move D4 B3)
       (valid_move D4 B5)
       (valid_move D4 C6)
       (valid_move D4 C2)
       (valid_move D4 F3)
       (valid_move D4 F5)
       (valid_move D4 E6)
       (valid_move D4 E2)
       (valid_move E4 C3)
       (valid_move E4 C5)
       (valid_move E4 D6)
       (valid_move E4 D2)
       (valid_move E4 G3)
       (valid_move E4 G5)
       (valid_move E4 F6)
       (valid_move E4 F2)
       (valid_move F4 D3)
       (valid_move F4 D5)
       (valid_move F4 E6)
       (valid_move F4 E2)
       (valid_move F4 H3)
       (valid_move F4 H5)
       (valid_move F4 G6)
       (valid_move F4 G2)
       (valid_move G4 E3)
       (valid_move G4 E5)
       (valid_move G4 F6)
       (valid_move G4 F2)
       (valid_move G4 H6)
       (valid_move G4 H2)
       (valid_move H4 F3)
       (valid_move H4 F5)
       (valid_move H4 G6)
       (valid_move H4 G2)
       (valid_move A5 C4)
       (valid_move A5 C6)
       (valid_move A5 B7)
       (valid_move A5 B3)
       (valid_move B5 A7)
       (valid_move B5 A3)
       (valid_move B5 D4)
       (valid_move B5 D6)
       (valid_move B5 C7)
       (valid_move B5 C3)
       (valid_move C5 A4)
       (valid_move C5 A6)
       (valid_move C5 B7)
       (valid_move C5 B3)
       (valid_move C5 E4)
       (valid_move C5 E6)
       (valid_move C5 D7)
       (valid_move C5 D3)
       (valid_move D5 B4)
       (valid_move D5 B6)
       (valid_move D5 C7)
       (valid_move D5 C3)
       (valid_move D5 F4)
       (valid_move D5 F6)
       (valid_move D5 E7)
       (valid_move D5 E3)
       (valid_move E5 C4)
       (valid_move E5 C6)
       (valid_move E5 D7)
       (valid_move E5 D3)
       (valid_move E5 G4)
       (valid_move E5 G6)
       (valid_move E5 F7)
       (valid_move E5 F3)
       (valid_move F5 D4)
       (valid_move F5 D6)
       (valid_move F5 E7)
       (valid_move F5 E3)
       (valid_move F5 H4)
       (valid_move F5 H6)
       (valid_move F5 G7)
       (valid_move F5 G3)
       (valid_move G5 E4)
       (valid_move G5 E6)
       (valid_move G5 F7)
       (valid_move G5 F3)
       (valid_move G5 H7)
       (valid_move G5 H3)
       (valid_move H5 F4)
       (valid_move H5 F6)
       (valid_move H5 G7)
       (valid_move H5 G3)
       (valid_move A6 C5)
       (valid_move A6 C7)
       (valid_move A6 B8)
       (valid_move A6 B4)
       (valid_move B6 A8)
       (valid_move B6 A4)
       (valid_move B6 D5)
       (valid_move B6 D7)
       (valid_move B6 C8)
       (valid_move B6 C4)
       (valid_move C6 A5)
       (valid_move C6 A7)
       (valid_move C6 B8)
       (valid_move C6 B4)
       (valid_move C6 E5)
       (valid_move C6 E7)
       (valid_move C6 D8)
       (valid_move C6 D4)
       (valid_move D6 B5)
       (valid_move D6 B7)
       (valid_move D6 C8)
       (valid_move D6 C4)
       (valid_move D6 F5)
       (valid_move D6 F7)
       (valid_move D6 E8)
       (valid_move D6 E4)
       (valid_move E6 C5)
       (valid_move E6 C7)
       (valid_move E6 D8)
       (valid_move E6 D4)
       (valid_move E6 G5)
       (valid_move E6 G7)
       (valid_move E6 F8)
       (valid_move E6 F4)
       (valid_move F6 D5)
       (valid_move F6 D7)
       (valid_move F6 E8)
       (valid_move F6 E4)
       (valid_move F6 H5)
       (valid_move F6 H7)
       (valid_move F6 G8)
       (valid_move F6 G4)
       (valid_move G6 E5)
       (valid_move G6 E7)
       (valid_move G6 F8)
       (valid_move G6 F4)
       (valid_move G6 H8)
       (valid_move G6 H4)
       (valid_move H6 F5)
       (valid_move H6 F7)
       (valid_move H6 G8)
       (valid_move H6 G4)
       (valid_move A7 C6)
       (valid_move A7 C8)
       (valid_move A7 B5)
       (valid_move B7 A5)
       (valid_move B7 D6)
       (valid_move B7 D8)
       (valid_move B7 C5)
       (valid_move C7 A6)
       (valid_move C7 A8)
       (valid_move C7 B5)
       (valid_move C7 E6)
       (valid_move C7 E8)
       (valid_move C7 D5)
       (valid_move D7 B6)
       (valid_move D7 B8)
       (valid_move D7 C5)
       (valid_move D7 F6)
       (valid_move D7 F8)
       (valid_move D7 E5)
       (valid_move E7 C6)
       (valid_move E7 C8)
       (valid_move E7 D5)
       (valid_move E7 G6)
       (valid_move E7 G8)
       (valid_move E7 F5)
       (valid_move F7 D6)
       (valid_move F7 D8)
       (valid_move F7 E5)
       (valid_move F7 H6)
       (valid_move F7 H8)
       (valid_move F7 G5)
       (valid_move G7 E6)
       (valid_move G7 E8)
       (valid_move G7 F5)
       (valid_move G7 H5)
       (valid_move H7 F6)
       (valid_move H7 F8)
       (valid_move H7 G5)
       (valid_move A8 C7)
       (valid_move A8 B6)
       (valid_move B8 A6)
       (valid_move B8 D7)
       (valid_move B8 C6)
       (valid_move C8 A7)
       (valid_move C8 B6)
       (valid_move C8 E7)
       (valid_move C8 D6)
       (valid_move D8 B7)
       (valid_move D8 C6)
       (valid_move D8 F7)
       (valid_move D8 E6)
       (valid_move E8 C7)
       (valid_move E8 D6)
       (valid_move E8 G7)
       (valid_move E8 F6)
       (valid_move F8 D7)
       (valid_move F8 E6)
       (valid_move F8 H7)
       (valid_move F8 G6)
       (valid_move G8 E7)
       (valid_move G8 F6)
       (valid_move G8 H6)
       (valid_move H8 F7)
       (valid_move H8 G6)
   )

   (:goal 
      (and 
         (visited A1)
         (visited A2)
         (visited A3)
         (visited A4)
         (visited A5)
         (visited A6)
         (visited A7)
         (visited A8)
         (visited B1)
         (visited B2)
         (visited B3)
         (visited B4)
         (visited B5)
         (visited B6)
         (visited B7)
         (visited B8)
         (visited C1)
         (visited C2)
         (visited C3)
         (visited C4)
         (visited C5)
         (visited C6)
         (visited C7)
         (visited C8)
         (visited D1)
         (visited D2)
         (visited D3)
         (visited D4)
         (visited D5)
         (visited D6)
         (visited D7)
         (visited D8)
         (visited E1)
         (visited E2)
         (visited E3)
         (visited E4)
         (visited E5)
         (visited E6)
         (visited E7)
         (visited E8)
         (visited F1)
         (visited F2)
         (visited F3)
         (visited F4)
         (visited F5)
         (visited F6)
         (visited F7)
         (visited F8)
         (visited G1)
         (visited G2)
         (visited G3)
         (visited G4)
         (visited G5)
         (visited G6)
         (visited G7)
         (visited G8)
         (visited H1)
         (visited H2)
         (visited H3)
         (visited H4)
         (visited H5)
         (visited H6)
         (visited H7)
         (visited H8))) 
   )